version: '3.8'

services:
  # This is our Python backend service
  backend:
    build: ./backend  # Tells it to build using the Dockerfile in ./backend
    ports:
      - "8000:8000"  # Maps your computer's port 8000 to the container's port 8000
    volumes:
      - ./backend:/app # (Optional) This mounts your code, so it auto-reloads!
    env_file:
      - ./backend/.env # This makes sure your OpenAI API key is loaded!

  # This is our JavaScript frontend service
  frontend:
    build: ./widget   # Tells it to build using the Dockerfile in ./widget
    ports:
      - "5500:80"    # Maps your computer's port 5500 to the container's port 80 (nginx default)
    volumes:
      - ./widget:/usr/share/nginx/html # (Optional) Mounts code for auto-reload
    depends_on:
      - backend        # Tells it to wait for the backend to start first